.TH DELECTUS 1 "07 August 2009"
.SH NAME
delectus \- Script for backing up delicious.com bookmarks
.SH SYNOPSIS
\fBdelectus\fP USERNAME [-c AMOUNT] [-f FILE] [-a|-h|-x]
.SH DESCRIPTION
Make a backup of USERNAME's last COUNT delicious.com
bookmarks and optionally save to FILE.
.SS OPTIONS
.TP
\fB-c --count \fIAMOUNT\fR
Number of bookmarks to retrieve, given as a digit. If set to 0 then all 
bookmarks are used (default).
.TP
\fB-a --adr\fP
Output backup as an Opera ADR file. Note that this format does not support
tags.
.TP
\fB-h --html\fP
Output backup as a Netscape HTML file. Most browsers, including Mozilla
Firefox, are able to import this format.
.TP
\fB-x --xbel\fP
Output the backup as an XBEL file (default). Note that this format does not
support tagging.
.SH BUGS
If two bookmarks have the same title, then only the earliest saved will be
backed up. If you get COUNT bookmarks, they aren't necessarily the COUNT
most recent.
.SH AUTHOR
Alec Schueler <johannalecschueler at googlemail dot com>
